### ISSUE TITLE
TriggererPod is not stateless with SnowflakeOperatorAsync

### ISSUE THREAD

**Issue by erdos2n** [astronomer/astronomer-providers#1017]
**Describe the bug**
When a new triggerer pod spins up and the old one dies, all SnowflakeOperatorAsync tasks are killed and either set to `fail` or `up_for_retry`. 

**To Reproduce**
1. Create SnowflakeOperatorAsync task
2. Kill TriggererPod
3. Task is externally killed

```
[queued]> finished (success) although the task says its queued. (Info: None) Was the task killed externally?
```

**Expected behavior**
The new triggerer pod should continue running this task without an issue

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Debian 

**Additional context**
We have observed this behavior with a triggerer pod that keeps failing its liveness probe check. Not sure if that's related, but either way, the triggerer pod should be stateless

**Comment by pankajastro** [comment]
From the initial investigation look like we use the cursor in the trigger to connect with Snowflake, not sure if owing a cursor session from a different pod would be possible. 
https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/hooks/snowflake.py#L172-L182

I believe you must not getting this issue with SnowflakeSqlApiOperatorAsync since we make http call here.

**Comment by phanikumv** [comment]
@erdos2n did you get a chance to look into above comment?

**Comment by erdos2n** [comment]
Hi @phanikumv, 
I am not getting GitHub notifications, but  I have not see this yet. This is a reported bug and the only use case has been the SnowflakeOperatorAsync. Not sure if this happens when using the SnowflakeSqlApiOperatorAsync.

**Comment by vatsrahul1001** [comment]
As we are deprecating providers, this might not be needed now. closing this
