### ISSUE TITLE
Handle soft fail for sensors

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#1170]
currently, we always fail in execute_comeplet if trigger a yield error which not respect  the soft_fail sensors param.

**Comment by phanikumv** [comment]
@utkarsharma2 lets make progress on this

**Comment by infohash** [comment]
Is this the reason why 'S3KeySensorAsync` goes to failed state instead of skipped state when `airflow.exceptions.TaskDeferralError: Trigger/execution timeout` occurs and `soft_fail` is set to `True`? I encountered this recently and I assumed it that it is by design to alert the user about missing bucket keys. But I agree, it should go to skipped state if soft_fail is set to `True`.

**Comment by infohash** [comment]
@pankajastro I tested soft fail for `S3KeySensorAsync` and it is not respecting `soft_fail` when the task execution times out and `airflow.exceptions.TaskDeferralError: Trigger/execution timeout` is raised. I tested it with both `wildcard_match` and `use_regex` flag.

**Comment by infohash** [comment]
I have tested it in airflow 2.7.1. It has been fixed in upstream by apache/airflow#33196 merged in 2.7.1 release.

**Comment by pankajastro** [comment]
Thanks for letting us know!
