### ISSUE TITLE
astronomer-providers not pinning airflow version (updating current setup)

### ISSUE THREAD

**Issue by alejandrofm** [astronomer/astronomer-providers#1322]
**Describe the bug**
Installing Astronomer providers on an Airflow image downloads the last version of airflow it has pinned (>=2.2.0)

**To Reproduce**
1. install Airflow < last version
2. Install Airflow providers on the same environment

**Expected behavior**
Airflow needs to be installed to install astronomer-providers, so avoid installing Airflow, and issue a warning that Airflow >=2.2.0 needs to be present.

**Desktop (please complete the following information):**
 - Currently using official 2.7.0 Python 3.10 image

**Comment by pankajastro** [comment]
Hey @alejandrofm I have published some constraints file https://github.com/astronomer/astronomer-providers/releases/tag/constraints-1.18.0 can you please try to use it.

**Comment by alejandrofm** [comment]
Hi, @pankajastro will look at the constraints, we are installing with poetry at this moment, and the thing that makes me raise this issue is: if Astronomer is a provider for Airflow, why does it install Airflow? it should not try to install the main package.
If I'm trying to install an add-on for an app I don't have, it should not install the full app but, at most, warn me about it.
For example Amazon-providers:
https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html
that states the minimum version, but will not update the current Airflow release.
Also, it makes it easier to not make mistakes.
In my current install schema (not the best, I know) I have to pin the airflow version on the toml for astronomer-providers to make sure that it does not try to update Airflow.

**Comment by pankajastro** [comment]
1. The Astronomer provider depends on the Airflow providers, which, in turn, has Airflow as a dependency. Therefore, even if we remove it from our configuration, it will still get installed due to the upstream dependency.
2. We also leverage certain core features of Airflow within the providers, and I believe this is the primary reason

We have just released 1.19.0  which has pin the minimum Airflow, Python and upstream providers version.

I'll close this issue for now but feel free to open a new one if still face any issues. thank you!
