### ISSUE TITLE
Debug snowflake flaky test 

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#1383]
looks like sometimes we have race conditions in snowflake table operation or running query and because of that our **snowflake_dag** is failing 

test result: https://astronomer.slack.com/archives/C037VQ1HCHZ/p1702602799122619

**Comment by vatsrahul1001** [comment]
@pankajkoti can you add your RCA here

**Comment by pankajkoti** [comment]
The `snowflake_op_multiple_query_in_one_run` task in the `example_snowflake` fails quite often.

This tasks tries to submit a sql that has multiple statements in it.
The SQL is:
```
MULTIPLE_QUERY_IN_ONE_RUN = (
    f"CREATE OR REPLACE TRANSIENT TABLE {SNOWFLAKE_SAMPLE_TABLE_MULTI} (name VARCHAR(250), id INT);"
    f"INSERT INTO {SNOWFLAKE_SAMPLE_TABLE_MULTI} VALUES ('name', 1);"
    f"DROP TABLE {SNOWFLAKE_SAMPLE_TABLE_MULTI};"
)
```

As per the hook code's run [method](https://github.com/astronomer/astronomer-providers/blob/1ccef0fc9fe8d5a1f3678dfe7a79644e77d652d6/astronomer/providers/snowflake/hooks/snowflake.py#L87), it submits each of the 3 statements above in a loop to Snowflake. However, once these queries are submitted to Snowflake, they run in an async fashion as individual queries without waiting for each other. As a result, it may happen that the insert statement runs before the create table and then it fails as the table has not yet been created. It may also happen that the drop statement runs before the create statement finishes. In such cases, it complains that the table does not exist.

I think the above example SQL query is a bad example to demonstrate the capability of the operator to runs multiple SQL statements. The example needs to be updated to include multiple statements in the query that do not depend on each other so that when they run in an async fashion individually they succeed well.

**Comment by pankajkoti** [comment]
As seen in the screenshot below from Snowflake history, the queries get submitted individually, they start at the same time, but each one has different finish time (execution time), dependent queries fail
[``](<img width="1719" alt="Screenshot 2023-12-18 at 1 44 02 PM" src="https://github.com/astronomer/astronomer-providers/assets/10206082/31b8a1d1-4af3-46fd-a36f-de1784acda1b">)
