### ISSUE TITLE
Enhance Integration Test Suite

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#153]
**Acceptance Criteria:**
- [x] Automate spinning  staging instance daily at the scheduled time from circleci so that  integration test will run on updated code
- [ ] Create and delete staging env
  - [ ] Create staging env from circleci
  - [ ] Automate creating connections(maybe through circleCI env variables or any other alternative approach) and 
  - [ ] delete staging env from circle ci
- [x] Remove redundant example code from amazon emr 
- [x] Integrate the integration tests with astro-cloud
- [ ] Publish a more informative and clean test report
- [ ] Decide whether to manually register dag in master dag or automatic trigger it 
- [ ] Check the feasibility of using the Turbulence Framework

**Comment by pankajastro** [comment]
Draft PR for automatic spinning staging instance https://github.com/astronomer/astronomer-providers/pull/207

**Comment by pankajastro** [comment]
> Publish a more informative and clean test report

Initially, I thought of embedding HTML code in the slack message so that I can format the report as per my wish but It does not work. Slack has its own syntax we can't format it toggle button.

> Decide whether to manually register dag in master dag or automatic pick and trigger it

- Grouping DAG will be not easy in this case.
- All DAG will trigger in parallel. 
- We need to bit of testing redshift SQL and redshift SQL for this. 
- Dataprocks DAG has one unused task that looks weird in the master DAG UI
I have pushed changes here https://github.com/astronomer/astronomer-providers/tree/test_automatic_dag_pick

**Comment by pankajastro** [comment]
> Integrate the integration tests with astro-cloud

PR: https://github.com/astronomer/astronomer-providers/pull/244

**Comment by phanikumv** [comment]
Pending: Enable deployment to astro-cloud, rest of the changes needed are done.

**Comment by phanikumv** [comment]
Implementing pending tasks in #266
