### ISSUE TITLE
Deprecate `S3PrefixSensor` and `S3KeySizeSensor` in favor of `S3KeySensor`

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#202]
Refer to https://github.com/apache/airflow/pull/22737 and make changes to async versions wherever applicable

**Comment by bharanidharan14** [comment]
Look for the Latest release in OSS and Deprecate in Astronomer Provider repo as well

**Comment by bharanidharan14** [comment]
Went through this PR  #22737 , some changes has to be done in the `S3KeySensorAsync`, because the `S3KeySensor` sync version has the combination of `S3PrefixSensor` and `S3KeySensor`. Its not only deprecating the `S3PrefixSensorAsync` and `S3KeySizeSensor`, but also we need to incorporate the changes what is in sync version. so changing the story estimation point.

**Comment by bharanidharan14** [comment]
Need to add async decorator function which will be used in current changes

**Comment by bharanidharan14** [comment]
Deprecated S3PrefixSensor and S3KeySensor. Made changes to the `S3KeySensorAsync` need test it

**Comment by bharanidharan14** [comment]
Added PR: https://github.com/astronomer/astronomer-providers/pull/577
