### ISSUE TITLE
SnowflakeOperatorAsync commits before status is received from the submitted queries.

### ISSUE THREAD

**Issue by ReadytoRocc** [astronomer/astronomer-providers#239]
**Describe the bug**
Currently, if `get_autocommit is True`, the `SnowflakeHookAsync` runs `conn.commit()` before status is received that the queries are complete. [Code Snippet](https://github.com/astronomer/astronomer-providers/blob/5cf53b2371240545d0fea603b03b482b64b77790/astronomer/providers/snowflake/hooks/snowflake.py#L79-L80).

**Expected behavior**
I would expect that `commit` is run once the queries are confirmed to have reached the expected status (e.g. successfully completed). Using the `SnowflakeOperatorAsync` as an example, `commit` would be run in the [`execute_complete`](https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/snowflake/operators/snowflake.py#L76-L96) method.

**Comment by ReadytoRocc** [comment]
Team, wanted to note that enforcing [`autocommit`](https://github.com/astronomer/astronomer-providers/blob/1.2.0/astronomer/providers/snowflake/hooks/snowflake.py#L57) to be `True` should ensure that this happens in the same session. In this case, we would need to use the context manager of the underlying Snowflake connection. In the connection's [`__exit__`](https://github.com/snowflakedb/snowflake-connector-python/blob/v2.7.6/src/snowflake/connector/connection.py#L1364-L1372) method we see that it should `commit` if `autocommit` is set.

**Comment by kaxil** [comment]
This might not be possible as the Query is submitted with `autocommit` on the worker and the control goes to Trigger and back to worker. In this case, it is not possible to preserve the "Connection"/Transaction

**Comment by bharanidharan14** [comment]
Current Async implementation creates a sync connection execute queries, gets the query ids and close the connection, to poll for the query status, trigger creates async connection and polls for the status by query id, snowflake allows to submit the query from one connection and retrieves the results from a different connection, So as  per @kaxil  comment it may not be possible to submit the query with `autocommit`, still investigation on this issue will keep posted

**Comment by bharanidharan14** [comment]
@ReadytoRocc on this issue did further investigation, I have tried few steps.
- creating connection in operator and send to it hook, execute the query get the query_id back 
- once the query id is available send the query id and connection object to Trigger, the connection is `None` in trigger because we can't send a class or connection object to the trigger, since it is not a JSON serialisable.
 Another way I tried is 
- Creating the connection in operator and sending it to hook and executing the query and in trigger creates the async connection, polls for the status and raise an event back to  worker with status.
- In `execute_complete`  the event is captured, tried to get the same connection, due to the same reason the connection object is `None`, since the response from the trigger is also not JSON serialisable.

I have created the flow chart for better understanding, please take look it.
https://lucid.app/lucidchart/a837aae1-8c2d-43ac-9ad5-1c8f101d833b/edit?invitationId=inv_10f28472-25bf-4777-96dd-62eaf2355389
![Screenshot 2022-04-28 at 10.41.17 AM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/84cf4250-b309-4921-905e-6009f6241be6)
