### ISSUE TITLE
Fix failing example_emr_eks_pi_job example DAG

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#257]
The example_emr_eks_pi_job is failing as part of our intergration tests run.
As part of the investigation logs, the shell script Bash Operator seems to having some errors not being raised up and letting the task state shown to be successful.
Understand the DAG, debug the issue across tasks in the DAG and make it working.

**Comment by pankajkoti** [comment]
Have set failure raise for shell script in the PR: https://github.com/astronomer/astronomer-providers/pull/259

However, cloud formation template is not succeeding with below failure reason:
` AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Resource handler returned message: \"[Issue(Code=AsgInstanceLaunchFailures, Message=You've reached your quota for maximum Fleet Requests for this account. Launching EC2 instance failed., ResourceIds=[eks-ng-a0731f88-2ec026b0-8620-cc3d-82e3-dee3ed01e00a]), Issue(Code=NodeCreationFailure, Message=Instances failed to join the kubernetes cluster, ResourceIds=[DUMMY_11448ab7-f2d5-42a7-a6cc-0d74ccb2e8e9, DUMMY_1bb6f31e-92c8-43d5-9ca3-8e815cbff947, DUMMY_2a5d16f9-291c-4d58-bf35-2eb5c0db88f5, DUMMY_4e4b490f-ef51-4d5b-87a5-3a5141ac6f9c, DUMMY_77a3e8d7-3af0-49e6-afa5-7c5ebc9a0eeb, DUMMY_7e88602e-c7f8-4d6a-943b-5f5078a4eb3f, DUMMY_a129f26a-1a81-4b5e-9c84-2285d8734a8f, DUMMY_abb67e19-d841-4bd0-ad05-5418f73149d1, DUMMY_ae850f0d-0693-4772-9d9b-4f4d442bab0e, DUMMY_ff345f8f-3468-4f2b-b8cf-ac1560c4150d])] (Service: null, Status Code: 0, Request ID: null, Extended Request ID: null)\" (RequestToken: 98ef1611-2341-fd34-ef08-4e8970c34e47, HandlerErrorCode: GeneralServiceException)"`

**Comment by pankajkoti** [comment]
Adding @bharanidharan14 as assignee too as he is trying this on his local.

**Comment by pankajkoti** [comment]
@dstandish suggested to try a smaller instance. But, we still are facing the same issue. He further suggested to check with @danielhoherd and/or speak to AWS. I will connect with @danielhoherd and check if he can help us here. Parallelly, I have created an AWS case for our account: https://us-east-1.console.aws.amazon.com/support/home?region=us-east-2#/case/?displayId=9973194951&language=en

**Comment by danielhoherd** [comment]
I don't have any special knowledge about this. The error seems pretty clear though: "You've reached your quota for maximum Fleet Requests for this account." My first step would be to make that request that @pankajkoti made.

We've run into this kind of thing in prod-cloud in GCP, and requesting an increase is the only solution.

**Comment by phanikumv** [comment]
- We are not sending the VIRTUAL_CLUSTER_ID to the `example_delete_eks_cluster_and_role_policies` shell script from the DAG. Due to this, if a virtual cluster already exists the delete shell script isn't cleaning up properly.

`[2022-05-02, 17:42:13 UTC] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sh $AIRFLOW_HOME/dags/example_delete_eks_cluster_and_role_policies.sh ']
[2022-05-02, 17:42:13 UTC] {subprocess.py:85} INFO - Output:
[2022-05-02, 17:42:19 UTC] {subprocess.py:89} INFO - 
[2022-05-02, 17:42:19 UTC] {subprocess.py:89} INFO - usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
[2022-05-02, 17:42:19 UTC] {subprocess.py:89} INFO - To see help text, you can run:
[2022-05-02, 17:42:19 UTC] {subprocess.py:89} INFO - 
[2022-05-02, 17:42:19 UTC] {subprocess.py:89} INFO -   aws help
[2022-05-02, 17:42:19 UTC] {subprocess.py:89} INFO -   aws <command> help
[2022-05-02, 17:42:19 UTC] {subprocess.py:89} INFO -   aws <command> <subcommand> help
[2022-05-02, 17:42:19 UTC] {subprocess.py:89} INFO - 
[2022-05-02, 17:42:19 UTC] {subprocess.py:89} INFO - aws: error: argument --id: expected one argument
`

`aws emr-containers delete-virtual-cluster --id $VIRTUAL_CLUSTER_ID`

VIRTUAL_CLUSTER_ID is coming as none during run-time

- create_emr_virtual_cluster_func should delete existing virtual clusters and then create one. 

`[2022-05-02, 17:42:10 UTC] {example_emr_eks_containers_job.py:60} ERROR - Error while creating EMR virtual cluster
Traceback (most recent call last):
  File "/usr/local/airflow/dags/example_emr_eks_containers_job.py", line 50, in create_emr_virtual_cluster_func
    response = client.create_virtual_cluster(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the CreateVirtualCluster operation: A virtual cluster already exists in the given namespace`
