### ISSUE TITLE
[SPIKE/RESEARCH] Approach for building extractors

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#330]
Reference documents:
Document shared from @julienledem https://docs.google.com/document/d/1vPsvHejQ24xTbzpz_LYSf0_ixk9oUuBiEUHVEaF9J2U/edit

Document drafted by @pankajkoti for discussing the approach: https://docs.google.com/document/d/1xNgOXUeOy25C0zi-NPkxdavk_lTq394TgjhelHJRrBM/edit

**Comment by pankajkoti** [comment]
Connect with @denimalpaca , @conorbev , & @julienledem to discuss current implementation and gather inputs for this story.
Post that, I will collate the inputs and propose an approach.

**Comment by pankajkoti** [comment]
Met @denimalpaca to understand his work. @conorbev has setup a meeting on Friday evening India time together with @julienledem & @howardyoo to discuss further on this.

Meantime I am trying to build the extractor in OL repo and use in providers repo astro-runtime environment.

**Comment by pankajkoti** [comment]
@conorbev I tried adding extractor in the OpenLineage repo and still it warns that extractor not found. Can I get some help from someone? Not able to tag Maciej here as his not part of our organisation. I have reached out to him over Slack; awaiting his reply.

**Comment by pankajkoti** [comment]
@julienledem has the opinion that each of the operators should emit their own lineage data to OL. And hence, the code would reside together with each of the sync/async operator in Airflow(sync operators)/Astronomer-providers(async-operators) repository. These events need to be transformed by the operator itself that would have a standard contract with OL.

I will discuss this approach with @kaxil and @phanikumv

**Comment by pankajkoti** [comment]
Following topics are in discussion:
1. How do we plan to emit lineage events from the Airflow ecosystem? Will the approach be similar to the existing approach where OL hooks into Airflow and runs the extractor post the operator has finished processing?
Response from @julienledem : The event sending should be centralised in the OL listener. Ideally in the future it can be bundled in Airflow and just a configuration to turn on

2. We might need to have a formal proposal to get the Airflow community to vote upon if they agree to have OL as the default lineage backend. Meanwhile, would it be okay to have all the extractors in astronomer-providers repository for both sync & async operators or have a separate repository store for these extractors called something like astronomer-ol-extractors?
Response from Julien: agreed, the best would be the airflow community voting for adopting OL as the standard. In the meantime, I would put the extractors in the same package as the operators they are for so that they stay in sync. (ie: astronomer-providers for the async operators) but putting them in OL itself would work too.

**Comment by pankajkoti** [comment]
We will take the approach mentioned in the above [comment](https://github.com/astronomer/astronomer-providers/issues/330#issuecomment-1145597008). Closing the ticket.
