### ISSUE TITLE
Fix EMR EKS example DAG failure

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#410]
EMR EKS DAG is failing with below error:

`[2022-05-24, 00:26:46 UTC] {example_emr_eks_containers_job.py:58} ERROR - Error while creating EMR virtual cluster
Traceback (most recent call last):
  File "/usr/local/airflow/dags/example_emr_eks_containers_job.py", line 48, in create_emr_virtual_cluster_func
    response = client.create_virtual_cluster(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the CreateVirtualCluster operation: A virtual cluster already exists in the given namespace`

**Comment by bharanidharan14** [comment]
Added condition to check for the virtual cluster in the namespace before creating it and need to test it in flow and check is any other issues is occurring

**Comment by bharanidharan14** [comment]
Created a pre-step to delete the EKS cluster and EMR virtual cluster before creating and testing

**Comment by bharanidharan14** [comment]
In long running task I getting `the maximum number of VPC has been reached` error

**Comment by bharanidharan14** [comment]
![Screenshot 2022-06-28 at 6.16.03 AM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/9184f310-f368-44ba-85c8-639cb835dc79)

**Comment by bharanidharan14** [comment]
![Screenshot 2022-06-29 at 12.50.46 AM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/eed779fd-4ad8-4416-8467-104cc43a1188)

**Comment by bharanidharan14** [comment]
[Uploading... Screenshot 2022-06-29 at 12.52.06 AM.png]

**Comment by bharanidharan14** [comment]
Default quota VPCs per region is 5 and EC2-VPC Elastic IPs default is 5

**Comment by bharanidharan14** [comment]
Elastic IPs default is 5 per region, this can be increased, as of now all the 5 is used and none of the instance is using it the no of instance running is 0 as per the below image, we can increase the Elastic IP limit or we delete this IPs and run the DAG again
 ![Screenshot 2022-07-07 at 11.00.26 AM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/f4c79c3a-9173-4c7f-b897-5779f2c09f28)
![Screenshot 2022-07-07 at 11.01.52 AM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/8a9c63a3-8d68-46f8-a8df-7ff55243a680)

**Comment by pankajkoti** [comment]
In my opinion, we should check why these Elastic IPs are getting created. If Elastic IPs are created and not associated to any instance, they get charged: https://aws.amazon.com/premiumsupport/knowledge-center/elastic-ip-charges/

So if no one is using it, we should delete them and also check why these are getting created in the first place so that they are not re-created & remain unused.

**Comment by bharanidharan14** [comment]
On this issue there was an existing  Elastic IP's and Unused VPC were not deleted properly while deleting the EMR-EKS cluster so the `create_eks_cluster_kube_namespace_with_role` step was throwing `AddressLimitExceed` error. airflow retries for the failed job, while retrying the same step the task is trying to create cluster so that time 
`An error occurred (ValidationException) when calling the CreateVirtualCluster operation: A virtual cluster already exists in the given namespace` error is occurring to fix this deleted unused VPC and  Released the Unassociated Elastic IP's so the `create_eks_cluster_kube_namespace_with_role` is working as expected

**Comment by bharanidharan14** [comment]
On the same DAG there was step `run_em_container_job` is running for long time and the job is not getting updated or completed which was working earlier. Did some analysis on this step tried running sample spark PY job in the EMR container and it can able to submit the job not able to complete it. It seems to be like permission issue while writing the log    ![Screenshot 2022-07-11 at 10.23.50 PM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/24433234-ad94-4965-9285-3bf424a866e0) 
![Screenshot 2022-07-11 at 11.05.19 PM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/2820ab80-4ebe-47e1-a1f4-2f8932d5bf49)

![Screenshot 2022-07-11 at 11.11.56 PM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/92d23002-7ebb-4bdb-87fd-c20dd8111182)

So closing the issue and raising IT ticket regarding the permission issue

**Comment by bharanidharan14** [comment]
Created Support Ticket
 https://us-east-1.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=10371549401&language=en

**Comment by pankajkoti** [comment]
Waiting for technical support from AWS.

**Comment by phanikumv** [comment]
As per the [this](https://docs.amazonaws.cn/en_us/emr/latest/EMR-on-EKS-DevelopmentGuide/emr-on-eks-dev-guide.pdf) link, we need to use `m5.xlarge` instance type for EMR EKS

**Comment by phanikumv** [comment]
Closing as the EMR EKS issue is resolved
