### ISSUE TITLE
[SPIKE/RESEARCH] Async Snowflake SQL Operator

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#412]
Today SnowflakeOperatorAsync does not support submitting multiple SQL statements sequentially, which is the behavior of the SnowflakeOperator.As a note, the Snowflake SQL API allows for submitting multiple SQL statements in a single request. In combination with aiohttp, this may be an option for creating a SnowflakeOperatorAsync that matches the query submission behavior of the SnowflakeOperator.

**Comment by bharanidharan14** [comment]
Started working on this, as per documentation trying to submit the create query and insert query in one single query

**Comment by ReadytoRocc** [comment]
Adding the related discussion here: https://github.com/astronomer/astronomer-providers/discussions/240.

Here are the docs I found through some research, regarding potential auth methods for this operator:
1. [Using Key Pair Auth](https://docs.snowflake.com/en/developer-guide/sql-api/authenticating.html#using-key-pair-authentication)
2. [Key Pair Auth and Rotation](https://docs.snowflake.com/en/user-guide/key-pair-auth.html)

**Comment by bharanidharan14** [comment]
Started implementing the separate SnowflakeSQLOperator by using AsyncA API call to existing connection won't be sufficient to make the API call we need find way in large context to support both SQL API type operator and snowflake connector type

**Comment by bharanidharan14** [comment]
Git hub repo link https://github.com/astronomer/astronomer-providers/tree/snowflake-multiple-sql

**Comment by bharanidharan14** [comment]
Finished coding part and pushed the code for snowflake SQL API operator, blocked with mapping public key to the snowflake user yesterday it was sorted by IT team now I need to test it with the Key's pair authentication

Git hub repo link[https://github.com/astronomer/astronomer-providers/tree/snowflake-multiple-sql](snowflake-multiple-sql)

**Comment by bharanidharan14** [comment]
Tested the code with key pair authentication, pushed the changes to `snowflake-multiple-sql` branch, with example DAG
Git hub repo linkhttps://github.com/astronomer/astronomer-providers/tree/snowflake-multiple-sql

**Comment by bharanidharan14** [comment]
@ReadytoRocc You can pull the code from `snowflake-multiple-sql` branch I have added example, you can pull the code and run the example DAG with `private key` in  the connection

**Comment by phanikumv** [comment]
@bharanidharan14 I dont see any PR created for this issue . If this needs to be delivered to customer, then we need to create PR and go through our release process. Can you please confirm what is the plan here?

**Comment by bharanidharan14** [comment]
@phanikumv I Pinged @ReadytoRocc on this, whether this has to be delivered to customer or not, once he confirm PR can be raised we can follow the release process. from our side I made sure this is developed as separate operator and its in working state with multiple Query Implementation and async execution.

**Comment by bharanidharan14** [comment]
@ReadytoRocc Can you add your comments on this

**Comment by ReadytoRocc** [comment]
Thanks @bharanidharan14. After some basic tests, this operator works well. Some thoughts:

1. I received a 403 error initially, because the `account` field in the connection did not include the `region`.
a. While this is noted in the [Snowflake docs](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#format-2-legacy-account-locator-in-a-region), the [SnowflakeHook](https://github.com/apache/airflow/blob/providers-snowflake/3.0.0/airflow/providers/snowflake/hooks/snowflake.py#L188) handles this by using the `region` configured in the `connection`.
b. This is something we may want to specifically note in the documentation.
2. We may want to offer an option to decrease the verbosity of the [logging](https://github.com/astronomer/astronomer-providers/blob/snowflake-multiple-sql/astronomer/providers/snowflake/hooks/snowflake_sql_api.py#L192) here.
a. For example, by default we could log some basic metadata about the query such as the `statementStatusUrl`, `message`, and `createdOn` fields.
b. If the full response is needed, this could be set via an argument.

**Comment by ReadytoRocc** [comment]
Thanks @bharanidharan14. After some basic tests, this operator works well. Some thoughts:

1. I received a 403 error initially, because the `account` field in the connection did not include the `region`.
a. While this is noted in the [Snowflake docs](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#format-2-legacy-account-locator-in-a-region), the [SnowflakeHook](https://github.com/apache/airflow/blob/providers-snowflake/3.0.0/airflow/providers/snowflake/hooks/snowflake.py#L188) handles this by using the `region` configured in the `connection`.
b. This is something we may want to specifically note in the documentation.
2. We may want to offer an option to configure the verbosity of the [logging](https://github.com/astronomer/astronomer-providers/blob/snowflake-multiple-sql/astronomer/providers/snowflake/hooks/snowflake_sql_api.py#L192) here.
a. For example, by default we could log some basic metadata about the statements such as the `statementStatusUrl`, `message`, and `createdOn` fields.
b. If the full response is needed, this could be set via an argument.

**Comment by bharanidharan14** [comment]
@ReadytoRocc Thanks for commenting
- I have added about `account locators identifiers` in the documentation, and user may want to add the account along with the region.
- if I logged the `statementStatusUrl`, `message`, and `createdOn` it will be logged in the trigger and web server UI won't be having this log
- I have logged the whole return response we can able to see the metadata of the query and rows got affected and more details like we see in sync snowflake operator
- @phanikumv your thought on setting argument for logging the full response

we need your thoughts whether this operator can be open sourced ?

**Comment by bharanidharan14** [comment]
As per Discussion with @ReadytoRocc This Async Snowflake SQL Operator works as the expected, it can able submit multiple SQL statements sequentially, and poll for the status, and this operator can be released as  open source operator along with few requirements fix. so closing this ticket
