### ISSUE TITLE
Implement Azure Synapse Operator

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#565]
We need to build an async (or sync if async is not possible) operator(s) for Azure Synapse that can 

- Load files from blob and run query

See if there are other operators we can create.

- [x] For the WasbtoSynapse operator, I think it'll be really important to document all the different parameters that we want to set. in particular, we need to be clear what precedence is, just because there's so much that can be set in the datafactory UI. We'll need customer feedback to know for sure how to handle this, but to start, we should ensure it's clear that the mapping in the operator takes precedence over what's in the UI.

- [x] Additionally, there were a few times where my Airflow task succeeded but the data was not copied (because the underlying data factory failed). Can we make sure to add a link to the ADF monitor view, on successful and failed tasks, so that users can debug their tasks accordingly.

- [x] It's definitely worth making the WasbtoSynapse and SynapseSQL operators async. The data loads, using the bulk load methods were not very fast - even a 2GB file took upwards of a few minutes.

**Comment by rajaths010494** [comment]
https://github.com/astronomer/astronomer-providers/tree/azure-synapse

**Comment by pankajkoti** [comment]
Pipeline wait is tested.

Issue: Synapse job is failure, but operator is success: needs to be tested (probably need to raise an AirflowException if it's not a success state)

**Comment by pankajkoti** [comment]
@phanikumv is helping @rajaths010494 on this task.

**Comment by rajaths010494** [comment]
1. Added wait for status for adf pipeline
2. Added exception handling for synapse job failure
3. Added return value of query results to xcom

**Comment by rajaths010494** [comment]
For the WasbtoSynapse operator, I think it'll be really important to document all the different parameters that we want to set. in particular, we need to be clear what precedence is, just because there's so much that can be set in the datafactory UI. We'll need customer feedback to know for sure how to handle this, but to start, we should ensure it's clear that the mapping in the operator takes precedence over what's in the UI.
Additionally, there were a few times where my Airflow task succeeded but the data was not copied (because the underlying data factory failed). Can we make sure to add a link to the ADF monitor view, on successful and failed tasks, so that users can debug their tasks accordingly.
It's definitely worth making the WasbtoSynapse and SynapseSQL operators async. The data loads, using the bulk load methods were not very fast - even a 2GB file took upwards of a few minutes.

**Comment by rajaths010494** [comment]
On Point 2, added a link and error message so the user can see the details from logs. The link is an API get which needs authorisation. 
Added error message in log if any error message displayed on the ADF pipeline also in the logs.
On point 1, the precedences aren’t mentioned in the azure document but when the mappings can either be created from UI or programmatically. Have added a docstring for it.
For reference
https://docs.microsoft.com/en-us/azure/data-factory/copy-activity-schema-and-type-mappin

**Comment by rajaths010494** [comment]
Point 3 has been done for `WasbToSynapseOperatorAsync` but `SynpaseSQLOperator` doesn't have a supported library for async as of now.

**Comment by pankajkoti** [comment]
Closing as the relevant tasks are complete.
