### ISSUE TITLE
Add guidelines for example DAG in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#76]
Some of the rules that can be added are:-

- Include a long running query always in the example DAG.
- Include a clean up step at the start of the example DAG so that there wont be failures if the resources are already present.
- Run all the steps in example DAG even if a particular task fails.

**Comment by kaxil** [comment]
This can probably go under a `Coding style and best practices` like Airflow one https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#coding-style-and-best-practices

**Comment by kaxil** [comment]
Some more points that can be added:

- The Async version of the operator should ideally be easily swappable and no DAG-facing changes should be required apart from changing Import Paths.
- See if the official library supports async, if not find a third-party library that supports async calls. (You can give example of Snowflake where the official library did allow async whereas Google’s official libs didn’t)
- Inheriting the sync version of the operator wherever possible so boilerplate code can be avoided while keeping consistency. And then replacing the logic of the execute method
- Logging: Passing the Status of the task from Trigger to the Operator so the logs show up in the Task Logs since Triggerer logs don’t make it to Task Logs


And probably a separate section for **listing common pitfalls**

**Comment by phanikumv** [comment]
Please list down some common pitfalls and best practises as well.
Some of the points that I can recollect at the moment are:

1.using correct class path in trigger serialize method
2.Referencing issue link in the PR descriptions
3.Writing unit tests which respect the code coverage toleration
4.git commit messages aligned to open source standards
5.rebase frequently 
6.include some learnings on the mypy checks ( may be a concise explanation of what is currently being checked for , with few examples. Have a look at https://github.com/astronomer/astronomer-providers/commit/d244d5ae2ad1194ddbf40fb905d37178e6b4ab14)
