### ISSUE TITLE
[SPIKE/RESEARCH]: SSHOperator Async

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#985]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Based on Slack thread: https://astronomer.slack.com/archives/C0387PMM2E7/p1682499663769299?thread_ts=1678791011.643619&cid=C0387PMM2E7

**Describe alternatives you've considered**

**Additional context**

**Comment by pankajkoti** [comment]
some more discussion here: https://astronomer.slack.com/archives/C01UJJEN0P3/p1684843137371259

**Comment by pankajkoti** [comment]
As pointed by @jedcunningham to the docs that they say
```
From the docs:
You should assume that a trigger instance may run more than once (this can happen if a network partition occurs and Airflow re-launches a trigger on a separated machine). So you must be mindful about side effects. For example you might not want to use a trigger to insert database rows.

A trigger may be suddenly removed from one triggerer service and started on a new one, for example if subnets are changed and a network partition results, or if there is a deployment. If desired you may implement the cleanup method, which is always called after run whether the trigger exits cleanly or otherwise.
```

it looks to me trigger is not the right place to submit an SSH command but from my understanding, the command should have been externally submitted and the trigger should only poll for its status or else upon restart or upon moving it to a new triggerer service, it would rerun the command and would lead to duplicate operations.

**Comment by pankajkoti** [comment]
Waiting to sync up with @iamakashladdha to update on the complexities involved here.

**Comment by pankajkoti** [comment]
A good starting point would also be to check if the sync version of the provider https://airflow.apache.org/docs/apache-airflow-providers-ssh/stable/_api/airflow/providers/ssh/operators/ssh/index.html operates well on the users platforms.

Answer to the below questions would help in researching more about checking the feasibility:
1. What kind of environment can we expect to get? Can we get a UNIX-like environment? 
     If not, what is the environment like: a powershell or similar or something else?
2. Can we verify that the below command works well on the platform:
    `bash -c 'sleep 0 & pid=$!; disown %1 ; echo pid=$pid'`
3. Can we ensure that after SSHing to the windows host, we do not get a CMD.exe session, because that would have more uncertainties.

**Comment by pankajkoti** [comment]
We're awaiting user feedback on the above questions. An Email was sent on Monday, May 29 2023 for the same to our users.

**Comment by pankajkoti** [comment]
We got a response from the users that they no longer need this change. So, I am closing this.
